package com.tonotes.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val light_primary = Color(0xFF00658D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFC6E7FF)
val light_onPrimaryContainer = Color(0xFF001E2D)
val light_secondary = Color(0xFF4F616E)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD2E5F4)
val light_onSecondaryContainer = Color(0xFF0B1D28)
val light_tertiary = Color(0xFF62597C)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE8DDFF)
val light_onTertiaryContainer = Color(0xFF1E1635)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFCFCFF)
val light_onBackground = Color(0xFF191C1E)
val light_surface = Color(0xFFFCFCFF)
val light_onSurface = Color(0xFF191C1E)
val light_surfaceVariant = Color(0xFFDDE3EA)
val light_onSurfaceVariant = Color(0xFF41484D)
val light_outline = Color(0xFF71787E)

// Dark theme
val dark_primary = Color(0xFF82CFFF)
val dark_onPrimary = Color(0xFF00344B)
val dark_primaryContainer = Color(0xFF004C6B)
val dark_onPrimaryContainer = Color(0xFFC6E7FF)
val dark_secondary = Color(0xFFB6C9D8)
val dark_onSecondary = Color(0xFF21323E)
val dark_secondaryContainer = Color(0xFF374955)
val dark_onSecondaryContainer = Color(0xFFD2E5F4)
val dark_tertiary = Color(0xFFCCC1E9)
val dark_onTertiary = Color(0xFF332C4B)
val dark_tertiaryContainer = Color(0xFF4A4263)
val dark_onTertiaryContainer = Color(0xFFE8DDFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1E)
val dark_onBackground = Color(0xFFE2E2E5)
val dark_surface = Color(0xFF191C1E)
val dark_onSurface = Color(0xFFE2E2E5)
val dark_surfaceVariant = Color(0xFF41484D)
val dark_onSurfaceVariant = Color(0xFFC1C7CE)
val dark_outline = Color(0xFF8B9198)